ENV NPM_CONFIG_LOGLEVEL warn
ENV NPM_CONFIG_PREFIX=/node_modules
ENV PATH=$PATH:/node_modules/.bin
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE False
ENV PIP_NO_BINARY=psycopg2

RUN \
  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
  echo "deb https://deb.nodesource.com/node_12.x stretch main" > /etc/apt/sources.list.d/nodesource.list && \
  wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  apt-get -qq update && \
  apt-get -qq install nodejs > /dev/null && \
  rm -rf /var/lib/apt/lists/*

COPY install-tools.sh /
RUN /install-tools.sh

WORKDIR /

RUN poetry install

COPY package.json package-lock.json /
RUN npm install
